<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * @param $element
 * @param $second
 */
function tmgmTransifexPollTranslations(array &$form, FormStateInterface $form_state) {
  $job = $form_state->getFormObject()->getEntity();
  $controller = $job->getTranslator()->getPlugin();
  try{
    $controller->checkForTranslations($job);
  }catch(Exception $e){
      drupal_set_message('Error while retrieving the translations from Transifex:' . $e->getMessage());
  }
}
