options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 0
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    - ignore-non-standard: true
  no-warn: 0

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 0
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false

  # Style Guide
  border-zero: 2
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 4
  property-sort-order: 0
  quotes: 0
  shorthand-values: 2
  url-quotes: 0
  variable-for-property: 2
  zero-unit: 2
  pseudo-element: 0
  class-name-format: 0

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
